default_language_version:
    python: python3.8
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-yaml
      exclude: template.yaml
    - id: check-json
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: mixed-line-ending
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master  # or specific git tag
    hooks:
    - id: markdownlint # Configure in .mdlrc - Check markdown files and flag style issues
    - id: shellcheck   # Shell scripts conform to shellcheck
    - id: shfmt        # Check shell style with shfmt
-   repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: make test
      language: python
      types: [python]
      # args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
      # pass_filenames: false
      # stages: [commit]
-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.33.0  # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: .*template\.(json|yml|yaml)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.9
    hooks:
    -   id: validate-html
        args: [--remove-mustaches, --mustache-remover=jinja2]
